### ISSUE TITLE
Nengo_gui issues

### ISSUE THREAD

**Issue by chinhnguyen2018** [nengo/nengo-gui#994] opened 2018-09-27 18:49 UTC
Hi all,
I am using the the nengo 0.4.3, python 3.6+ and windows 10 + chrome 
However,  the nengo_gui has the issue when I try to open it, the browser is opened but can't connect to server or something like that, this makes my laptop crashed and reset automatically because of DPC_Watchdog_violation error. 
Sometimes, I can connect to the nengo server and nengo_gui is opened but the gui doesn't show correctly such as missing the wires, neurons, can't run simulations ... then I closed my terminal and browser and opened  nengo_gui again => laptop crashed and reset automatically. 
Can anyone help me and let me know what is happening with nengo_gui ?
I appreciate your help

**Comment by astoeckel** [comment] 2018-09-27 19:59
Fatal system errors such as the `DPC_Watchdog_violation` blue-screen of death are (at least in theory) never caused by user-space software such as Nengo. They are either the result of faulty drivers (often your video driver, since Chrome makes heavy use of the GPU) or damaged hardware (for example RAM, CPU, or motherboard). I fear there is no way we can help you with this issue. You should test another computer, reinstall Windows, or try another operating system.

Since this issue tracker is for bugs directly related to Nengo, but this is most likely a problem with your computer, I'm closing this issue. You may want to head over to the Nengo forum at https://forum.nengo.ai/ where we can have more general discussions.

**Closed by astoeckel** 2018-09-27 19:59 UTC

**Comment by chinhnguyen2018** [comment] 2018-09-27 21:02
Thank you for your feedback, it happened many many times when I ran the nengo or nengo_gui, i tried to run the nengo_gui --port 8888, it worked for the first time then i closed and opened the nengo again, the software was crashed and reset my laptop (I took me a week to figure out the issue before i posted the error here). This is the new laptop, it is working well and unless I run nengo or nengo_gui. My work laptop is Precision 7720. I asked IT about this and they have no ideas, they advised me don't run the nengo_gui again
Thank you

**Comment by astoeckel** [comment] 2018-09-27 22:30
Sorry, I probably wasn't clear enough with what I meant with "never caused by user-space software such as Nengo". It is well possible (and I totally believe your description) that user-space software triggers hard OS crashes, but the user-space software is never to blame for that, since it is one of the primary roles of the OS to prevent exactly this from happening. The root cause must be in a OS or hardware component. 

Corporate "security software" is often (at least partially) implemented as an OS driver and thus might cause the entire OS to crash, or in other words, make your computer *less* secure. This is a general problem with this kind of software.
