### ISSUE TITLE
Save as pdf

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo-gui#10] opened 2015-01-20 18:17 UTC
Make nice ways to save the layout to pdf/svg

**Comment by studywolf** [comment] 2015-08-22 10:12
it would also be nice to be able to save the response curves in the neuron details as a pdf easily

**Comment by jgosmann** [comment] 2015-08-22 17:17
Duplicate of #52?

**Comment by Seanny123** [comment] 2015-08-22 19:40
@jgosmann I think they refer to different scopes. One refers to saving the whole layout while the other refers to saving individual plots.

However, just to be the devil's advocate, the reason why we don't want the person to rely on screenshot software is that the screenshot might be too low resolution right?

**Comment by Seanny123** [comment] 2015-08-22 19:48
Also, in terms of flow, I'm assuming that people want a context menu for individual plots. For saving the layout, should that be a context menu in the background or a top-menu item?

**Comment by studywolf** [comment] 2015-08-22 23:32
yeah the screenshot is passable but it would be really nice to get a pdf /
svg so it looks clean after manipulating it for a presentation

**Comment by jgosmann** [comment] 2015-08-23 00:03
It should be possible to get the SVG parts as an SVG without additional libraries (which you could convert with an external tool to PDF or whatever you need).

**Comment by tcstewar** [comment] 2016-02-12 22:03
PR #656 did the SVG export, and you can convert that to pdf by opening it in a decent browser and exporting to PDF.

**Closed as completed by tcstewar** 2016-02-12 22:03 UTC
Labels: discussion
