### ISSUE TITLE
One some Macs (OS X 10.9.5) using trackpad right-click menu disappears

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-gui#474] opened 2015-07-08 14:47 UTC
When using Ctrl-click to do a right-click, the menu appears, but then immediately disappears when you try to move to select something.  The problem goes away when using a mouse.

**Comment by cchan987** [comment] 2015-07-08 15:31
Could this be potentially related to #338

**Comment by jgosmann** [comment] 2015-07-08 15:48
Works on my Mac (10.10.4).
#338 is not a Mac issue (happens also on Linux)

**Comment by krisfrenette** [comment] 2019-04-30 18:10
This is a duplicate of #338

**Closed by krisfrenette** 2019-04-30 18:10 UTC
