### ISSUE TITLE
Change localhost to 127.0.0.1:8080/

### ISSUE THREAD

**Issue by amaziying** [nengo/nengo-gui#21] opened 2015-01-22 21:34 UTC
There are compatibility issues with localhost on some machines.

**Comment by jgosmann** [comment] 2015-01-22 21:45
Can you provide more details? I think, 'localhost' is more future-proof because it can resolve to an iPv6 address (::1) instead of the IPv4 address.

**Comment by tcstewar** [comment] 2015-01-22 22:29
> Can you provide more details? I think, 'localhost' is more future-proof because it can resolve to an iPv6 address (::1) instead of the IPv4 address.

Ooo...  good point.  Forgot about that.  

The problem was that on his machine somehow the browser refused to resolve localhost and went to http://www.localhost.com/ instead.  I've never seen a computer do that before, and indeed, didn't even know it was possible.

**Comment by jgosmann** [comment] 2015-01-22 22:35
One could argue that it is problem with his configuration. [Maybe this one?](https://cdivilly.wordpress.com/2013/08/15/disable-firefox-redirecting-to-localhost-com/)

**Comment by tcstewar** [comment] 2015-01-22 22:41
> One could argue that it is problem with his configuration. Maybe this one?

Oh no....  that's exactly what's happening.  We pop open the browser window slightly before the server gets started, and so if firefox tries to open up the page before the server is ready, it doesn't respond to the initial request, gives up, and tries ```localhost.com``` and ```www.localhost.com``` instead.  Ouch.

So the real solution is to keep things aimed at ```localhost```, but not call ```webbrowser.open()``` until after we're sure the server is ready.  Otherwise we can hit this race condition.

**Comment by amaziying** [comment] 2015-01-22 23:44
So I tried the solution on the link Jan posted. The localhost no longer resolves to www.localhost.com <http://www.localhost.com/> but just localhost:8080 doesn’t work either. Only 127.0.0.1:8080 works for me…

**Comment by cchan987** [comment] 2015-07-03 15:54
Websocket now queries the document.URL in order to connect websockets.

**Comment by tcstewar** [comment] 2015-07-03 15:57
> Websocket now queries the document.URL in order to connect websockets.

That's not the problem here.  The problem is that the document URL itself doesn't work, not the websockets.

I haven't seen this problem in a while except on on Mac a few weeks ago.  But the fix was still to manually go to http://127.0.0.1:8080 rather than http://localhost:8080

**Comment by jgosmann** [comment] 2015-07-03 16:00
The IPython visualization waits until the server is started. So we might be able to reuse that code.

**Comment by tcstewar** [comment] 2015-07-03 16:01
> The IPython visualization waits until the server is started. So we might be able to reuse that code.

Possibly.  I'd like to have access to a machine where the problem exists, though, before trying to debug it, as I'm not 100% convinced that it's a startup time thing.

**Comment by jgosmann** [comment] 2015-07-03 17:44
How about inserting a `sleep` in the startup to see whether you can reproduce it? That doesn't guarantee that there is not an additional problem, but at least it allows to verify that part.

**Comment by tcstewar** [comment] 2015-07-03 17:55
> How about inserting a sleep in the startup to see whether you can reproduce it?

Ooo, good idea.. lemme try that...

Argh, nope, even with a 30-second sleep neither Firefox nor Chrome give up for me.  And it was never anywhere close to that amount of time in previous situations I've seen this in.

**Comment by tcstewar** [comment] 2015-07-03 17:57
So I think that puts me back to thinking this is an IPv4 vs IPv6 issue...  it might have been on a machine that was treating ```localhost``` as ```::1``` instead of as ```127.0.0.1```, and I'm pretty sure I haven't turned on support for IPv6 in swi.py.  So that might be all that's happening here.....

**Comment by Seanny123** [comment] 2016-07-01 17:44
Is this resolved by #673?

**Comment by jgosmann** [comment] 2016-07-01 17:58
No. It is still using `localhost` and does not support IPv6. Though, [IPv6 support is easy to turn on](https://gist.github.com/akorobov/7903307), but the websocket implementation has to be change too to accept those connections (shouldn't be too complicated either).

**Comment by tcstewar** [comment] 2017-01-10 03:04
This needs to get looked at again, especially since @jgosmann 's server refactoring.  It'd be great to have IPv6 support.  The initially reported issue seems very rare (and we don't currently have a machine that's exhibiting it), but my current belief is that if we had full IPv6 support, then the problem wouldn't happen.

**Comment by jgosmann** [comment] 2017-01-10 10:00
Seems like we're currently not supporting IPv6. Replacing IPv4 with IPv6 support would probably be easy with 2 or 3 lines changed, but supporting IPv4 *and* IPv6 is a bit harder. Here are some links with helpful information:

* https://bugs.python.org/issue17561
* https://code.activestate.com/recipes/578504-server-supporting-ipv4-and-ipv6/

**Comment by jgosmann** [comment] 2017-02-07 23:42
#864 adds dual stack IPv6 support. Not sure if that resolves this problem?

**Comment by jgosmann** [comment] 2018-07-10 20:11
Did anyone see this problem in the last year or can this be closed?

**Comment by krisfrenette** [comment] 2019-04-22 18:16
As far as I can tell, this issues hasn't come up again, and there has been no further update since the the last request so I am going to close this out.

**Closed as completed by krisfrenette** 2019-04-22 18:16 UTC
